name: bova_player_flutter
description: BovaPlayer Flutter UI
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  ffi: ^2.0.1
  path_provider: ^2.1.1
  file_picker: ^8.0.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  # 使用最新版本的 media_kit
  media_kit: ^2.0.1
  media_kit_video: ^2.0.1
  # media_kit_libs_video 会作为传递依赖自动引入
  # 字幕支持
  subtitle_wrapper_package: ^2.2.1
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/